# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 412)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(290, 20, 120, 80))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 118, 78))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(90, 140, 256, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(460, 150, 137, 194))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tag_edit = QtWidgets.QLineEdit(self.widget)
        self.tag_edit.setObjectName("tag_edit")
        self.verticalLayout.addWidget(self.tag_edit)
        self.play_button = QtWidgets.QPushButton(self.widget)
        self.play_button.setObjectName("play_button")
        self.verticalLayout.addWidget(self.play_button)
        self.save_button = QtWidgets.QPushButton(self.widget)
        self.save_button.setObjectName("save_button")
        self.verticalLayout.addWidget(self.save_button)
        self.next_button = QtWidgets.QPushButton(self.widget)
        self.next_button.setObjectName("next_button")
        self.verticalLayout.addWidget(self.next_button)
        self.prev_button = QtWidgets.QPushButton(self.widget)
        self.prev_button.setObjectName("prev_button")
        self.verticalLayout.addWidget(self.prev_button)
        self.quit_button = QtWidgets.QPushButton(self.widget)
        self.quit_button.setObjectName("quit_button")
        self.verticalLayout.addWidget(self.quit_button)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_play = QtWidgets.QAction(MainWindow)
        self.action_play.setObjectName("action_play")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_next = QtWidgets.QAction(MainWindow)
        self.action_next.setObjectName("action_next")
        self.action_prev = QtWidgets.QAction(MainWindow)
        self.action_prev.setObjectName("action_prev")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.action_open)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_play)
        self.menuFile.addAction(self.action_save)
        self.menuFile.addAction(self.action_next)
        self.menuFile.addAction(self.action_prev)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tag_edit.setPlaceholderText(_translate("MainWindow", "tag"))
        self.play_button.setText(_translate("MainWindow", "Play"))
        self.save_button.setText(_translate("MainWindow", "Save"))
        self.next_button.setText(_translate("MainWindow", "Next"))
        self.prev_button.setText(_translate("MainWindow", "Prev"))
        self.quit_button.setText(_translate("MainWindow", "Quit"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.action_open.setText(_translate("MainWindow", "Open Folder"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_play.setText(_translate("MainWindow", "Play Selection"))
        self.action_play.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.action_save.setText(_translate("MainWindow", "Save Selection"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_next.setText(_translate("MainWindow", "Next"))
        self.action_next.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.action_prev.setText(_translate("MainWindow", "Previous"))
        self.action_prev.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
