# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/soundannotator.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 750)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 574, 494))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.viewer = SpecViewer(self.scrollAreaWidgetContents)
        self.viewer.setGeometry(QtCore.QRect(30, 30, 59, 16))
        self.viewer.setText("")
        self.viewer.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.viewer.setObjectName("viewer")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.table = CSVTable(self.centralwidget)
        self.table.setGridStyle(QtCore.Qt.DotLine)
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.horizontalLayout.addWidget(self.table)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, -1, 5, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tag = QtWidgets.QLineEdit(self.centralwidget)
        self.tag.setObjectName("tag")
        self.verticalLayout.addWidget(self.tag)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setEnabled(False)
        self.playButton.setMaximumSize(QtCore.QSize(85, 16777215))
        self.playButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.playButton.setObjectName("playButton")
        self.verticalLayout_2.addWidget(self.playButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setEnabled(False)
        self.saveButton.setMaximumSize(QtCore.QSize(85, 16777215))
        self.saveButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_2.addWidget(self.saveButton)
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setEnabled(False)
        self.nextButton.setMaximumSize(QtCore.QSize(85, 16777215))
        self.nextButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.nextButton.setObjectName("nextButton")
        self.verticalLayout_2.addWidget(self.nextButton)
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setEnabled(False)
        self.prevButton.setMaximumSize(QtCore.QSize(85, 16777215))
        self.prevButton.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.prevButton.setObjectName("prevButton")
        self.verticalLayout_2.addWidget(self.prevButton)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_4.setStretch(0, 8)
        self.verticalLayout_4.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuActions = QtWidgets.QMenu(self.menubar)
        self.menuActions.setObjectName("menuActions")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        self.actionPlay.setEnabled(False)
        self.actionPlay.setObjectName("actionPlay")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setEnabled(False)
        self.actionSave.setObjectName("actionSave")
        self.actionNext = QtWidgets.QAction(MainWindow)
        self.actionNext.setEnabled(False)
        self.actionNext.setObjectName("actionNext")
        self.actionPrev = QtWidgets.QAction(MainWindow)
        self.actionPrev.setEnabled(False)
        self.actionPrev.setObjectName("actionPrev")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionExit)
        self.menuActions.addAction(self.actionPlay)
        self.menuActions.addAction(self.actionSave)
        self.menuActions.addAction(self.actionNext)
        self.menuActions.addAction(self.actionPrev)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scrollArea, self.tag)
        MainWindow.setTabOrder(self.tag, self.playButton)
        MainWindow.setTabOrder(self.playButton, self.saveButton)
        MainWindow.setTabOrder(self.saveButton, self.nextButton)
        MainWindow.setTabOrder(self.nextButton, self.prevButton)
        MainWindow.setTabOrder(self.prevButton, self.table)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "annotator"))
        self.tag.setPlaceholderText(_translate("MainWindow", "tag"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.prevButton.setText(_translate("MainWindow", "Prev"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuActions.setTitle(_translate("MainWindow", "Actions"))
        self.actionNew.setText(_translate("MainWindow", "New Session"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionPlay.setText(_translate("MainWindow", "Play Selection"))
        self.actionPlay.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSave.setText(_translate("MainWindow", "Save Selection"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionNext.setText(_translate("MainWindow", "Next"))
        self.actionNext.setShortcut(_translate("MainWindow", "Ctrl+Right"))
        self.actionPrev.setText(_translate("MainWindow", "Previous"))
        self.actionPrev.setShortcut(_translate("MainWindow", "Ctrl+Left"))
        self.actionLoad.setText(_translate("MainWindow", "Load Session"))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionExit.setText(_translate("MainWindow", "Exit Session"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+W"))
from csv_table import CSVTable
from spec_viewer import SpecViewer
